version: 0.2
phases:
  install:
    runtime-versions:
        dotnet: 2.2
  build:
    commands:
      - dotnet test ./HelloWorld.csproj
      - dotnet publish -c release -o ./build_output ./HelloWorld.csproj
artifacts:
  files:
    - build_output/*